spring:
  data:
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        password: 123456
        lettuce:
          pool:
            min-idle: 0
            max-idle: 8
            max-active: 8
            max-wait: -1ms
        timeout: 10000
        connectTimeout: 20000
  #如果你是基于zookeeper实现，那么做如下配置
  coordinate:
    zookeeper:
      zkServers: 127.0.0.1:2181
lock4j:
  acquire-timeout: 5000
  expire: 5000
  primary-executor: com.baomidou.lock.executor.RedisTemplateLockExecutor
