spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
fdfs:
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  thumbImage: #缩略图生成参数，可选
    width: 150
    height: 150
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
    - 192.168.100.5:22122

wx:
  mp:
    app-id: wx19b0485d2bd92651
    secret: 31e37f4fa06e1ac3accec00daf9a3b3b
    token: token
    aes-key:
    config-storage:
      redis:
        database: 1
        host: 127.0.0.1
        port: 6379
        password: 123456
      type: redistemplate
  work-wx:
    corpId: ww21bfd7bab878da9c
    agentId: 1000002
    corpSecret: 1zD06EIzblxH4k9xids_YS_fc-7cSqQrFFurGDwU8xI

config:
  love:
    # 生日 yyyy-MM-dd 例如2001-01-18
    girlBirthday: 1985-08-07
    boyBirthday: 1985-09-27
    # 恋爱纪念日 格式同上
    day: 2015-04-27
  auth:
    username: xiaosi
    password: 1234561
  default:
    # 默认推送方式，默认企业微信 work 企业微信  mp 微信公众号
    push: work


api:
  qweather:
    # 用户认证key
    key: ba71d1015a6a4585bc2380e5e53eab85
    # LocationID
    locationId: 101020900

  tian:
    key: 9aa006226c6a606a375b0e6058c9e52d



