server:
  port: 8701

spring:
  application:
    name: gongzhonghao

  jackson:
    # 格式化全局时间字段
    date-format: yyyy-MM-dd HH:mm:ss
    # 指定时间区域类型
    time-zone: GMT+8
  data:
    redis:
      # IP，默认本地
      host: localhost
      database: 0
      port: 6379
      # 密码，没有就不填
      password: 123456
      # 连接超时时间（记得添加单位）
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8   #最大连接数据库连接数（设0或负值没有限制）默认8
          max-wait: -1ms  #最大建立连接等待时间（使用负值表示没有限制）。如果超过此时间将接到异常，默认-1
          max-idle: 8     #连接池中的最大空闲连接（设 0 为没有限制） 默认8
          min-idle: 0     #连接池中的最小空闲连接（设 0 为没有限制） 默认0
        shutdown-timeout: 100ms

api:
  wx:
    appId: wx19b0485d2bd92651
    appSecret: 31e37f4fa06e1ac3accec00daf9a3b3b
    userOpenid: oKIee6K9bDb7hT-Q8SNnAXnx3rfo
    msgTempId: 8kmETolj-KYzHyUD2-8wmE6PyBwUuvyk3E3GE_a_PuI

  qweather:
    # 用户认证key
    key: ba71d1015a6a4585bc2380e5e53eab85
    # LocationID
    locationId: 101020900

  tian:
    key: 9aa006226c6a606a375b0e6058c9e52d

  work-wx:
    corpId: ww21bfd7bab878da9c
    agentId: 1000002
    corpSecret: 1zD06EIzblxH4k9xids_YS_fc-7cSqQrFFurGDwU8xI

config:
  love:
    # 生日 yyyy-MM-dd 例如2001-01-18
    girlBirthday: 1985-08-07
    boyBirthday: 1985-09-27
    # 恋爱纪念日 格式同上
    day: 2015-04-27
  auth:
    username: xiaosi
    password: 1234561
  default:
    # 默认推送方式，默认企业微信 work 企业微信  mp 微信公众号
    push: work


# Sa-Token配置
sa-token:
  # token 名称 (同时也是cookie名称)
  token-name: token
  # token 有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token 临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: simple-uuid
  # 是否输出操作日志
  is-log: false

