spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
  thymeleaf:
    cache: false
  rabbitmq:
    host: ${quick.rabbitmq.host}
    port: ${quick.rabbitmq.port} # 端口
    virtual-host: ${quick.rabbitmq.virtual-host} # 虚拟主机
    username: ${quick.rabbitmq.username} # 用户名
    password: ${quick.rabbitmq.password} # 密码
    stomp:
      port: 15674

quick:
  rabbitmq:
    host: 127.0.0.1 #服务器ip地址（此处为虚拟机地址）
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: guest # 用户名
    password: guest # 密码
    listener:
      simple:
        acknowledge-mode: auto # 自动ack
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000ms # 初识的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数
          stateless: false # true无状态；false有状态。如果业务中包含事务，这里改为false
    publisher-confirm-type: CORRELATED # 交换机的确认
    publisher-returns: true # 队列的确认
